ALTER TABLE "BackgroundTask" ADD COLUMN IF NOT EXISTS "stage" TEXT;
ALTER TABLE "BackgroundTask" ADD COLUMN IF NOT EXISTS "stageProgress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "BackgroundTask" ADD COLUMN IF NOT EXISTS "stageDetail" TEXT;

ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "stage" TEXT;
ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "stageProgress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VideoJob" ADD COLUMN IF NOT EXISTS "stageDetail" TEXT;
